### ISSUE TITLE
How do I use the docs repo with this one on my development machine?

### ISSUE THREAD

**Issue by geoffreyvanwyk** [laravel-doctrine/laraveldoctrine.org#1]
I have setup laraveldoctrine.org, but cannot figure out how to integrate the docs repository.

**Comment by patrickbrouwers** [comment]
Out of the box it will pull the docs from the remote github repo.

If you want to have the docs locally, you will have to clone the repo. 
- Make a `/docs` folder 
- Inside the `/docs` folder, make a `1.0` folder.
- Clone the docs repo (your fork to be more specific) into `1.0`
- Edit .env and set `DOCS_LOCATION=` to the location of the docs (this can be IP, url) (leave of the 1.0 part of the url)
