### ISSUE TITLE
Auth::attempt works but user won't stay signed in

### ISSUE THREAD

**Issue by ludberg** [laravel-doctrine/laraveldoctrine.org#3]
First of, thanks for a great piece of software!

I have a problem with Auth::attempt when using Doctrine. Attempt works but if I do

```
return redirect()->intended('home');
```

I will be directed back to login as the user is not logged in. Please note that the out of the box-login page works. 

It doesn't matter whether or not I try to overwrite the standard identifier via

```
public function getAuthIdentifierName()
{
    return 'userid';
}
```

I'm following the instructions here: http://www.laraveldoctrine.org/docs/1.1/orm/auth

ORM: v2.5.4
laravel-doctrine/orm: 1.1.0
Laravel framework: 5.2.7

**Comment by josenicomaia** [comment]
@ludberg 
There are some redirect flags on the Laravel Auth.
Did you check it?
https://laravel.com/docs/5.1/authentication#included-authenticating

**Comment by patrickbrouwers** [comment]
Also please don't post issues at this repo, but in https://github.com/laravel-doctrine/orm
