### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by m-bymike** [laravel-doctrine/laraveldoctrine.org#5]
Hi!

Sorry, I don't know a better place to put this. 

![Certificate](https://user-images.githubusercontent.com/4008663/44088958-57dbd8f4-9fc5-11e8-848d-4a9566f9197e.png)

The certificate expired two days ago and I got a big red warning opening the site...

br, michael

**Comment by patrickbrouwers** [comment]
@josenicomaia can you have a look

**Comment by josenicomaia** [comment]
@m-bymike You are in the right place :)
Solving... Just a sec.

**Comment by patrickbrouwers** [comment]
Thanks @josenicomaia :)

**Comment by m-bymike** [comment]
Thanks! \o/
